include ../../build/modules.mk

MODULE = server
FILENAME = ${MODULE}.js
SOURCE = ${SOURCE_DIR}/jquery.${MODULE}.js
PRODUCTION = ${PRODUCTION_DIR}/${FILENAME}
DEVELOPMENT = ${DEVELOPMENT_DIR}/${FILENAME}

all:
	${WRAP} -c ${SOURCE} > ${DEVELOPMENT}
	${UGLIFYJS} ${DEVELOPMENT} > ${PRODUCTION}
